### ISSUE TITLE
Add Support to Subscribe to Topics

### ISSUE THREAD

**Issue by ghost** [Losant/losant-mqtt-python#1]
The MQTT protocol is based on the principle of publishing messages and subscribing to topics. 
Clients should be able to subscribe to a specific topic and to multiple topics using wildcards.

**Comment by InconceivableDuck** [comment]
Our clients wrap an underlying MQTT client to handle publishing and subscribing to Losant-specific topics and to properly form payloads in a way Losant understands. For instance, `send_state` publishes to `losant/DEVICE_ID/state` with a payload in the correct format. `add_event_observer` subscribes to `losant/DEVICE_ID/command` and will automatically parse the command payload into the correct form.

It's not a bad idea to also expose the publish and subscribe functions so users could use the broker directly.

As a workaround, you can access to the underlying MQTT client using `device._mqtt_client`, which is an instance of [Paho MQTT Client](https://github.com/eclipse/paho.mqtt.python). Once you have the client, you can publish and subscribe to any topics. Just make sure if you publish to Losant topics, they adhere our [MQTT spec](https://docs.losant.com/mqtt/overview/).
